//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ClientAttachedInvoiceSettlementDetail : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int ClientAttachedInvoiceSettlementID { get; set; }
        public int ClientInvoiceDetailID { get; set; }
        public int StockOutDetailID { get; set; }
        public int InvoiceQty { get; set; }
        public Nullable<int> SettlementQty { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> SettlementAmount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual ClientAttachedInvoiceSettlement ClientAttachedInvoiceSettlement { get; set; }
        public virtual ClientInvoiceDetail ClientInvoiceDetail { get; set; }
        public virtual StockOutDetail StockOutDetail { get; set; }
    }
}
