//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ClientInfoProductSetting : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int ClientInfoID { get; set; }
        public int ProductID { get; set; }
        public int ProductSpecificationID { get; set; }
        public Nullable<double> HighPrice { get; set; }
        public Nullable<double> BasicPrice { get; set; }
        public Nullable<bool> UseFlowData { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DeptDistrictID { get; set; }
        public Nullable<int> MonthlyTask { get; set; }
        public Nullable<double> RefundPrice { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual Product Product { get; set; }
        public virtual ProductSpecification ProductSpecification { get; set; }
        public virtual ClientInfo ClientInfo { get; set; }
        public virtual Department Department { get; set; }
    }
}
