//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ClientTaskRefundApplication : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int ClientUserID { get; set; }
        public int ClientCompanyID { get; set; }
        public int ProductID { get; set; }
        public int ProductSpecificationID { get; set; }
        public int TaskQty { get; set; }
        public int StockOutQty { get; set; }
        public Nullable<bool> UseFlowData { get; set; }
        public Nullable<int> BackQty { get; set; }
        public Nullable<decimal> RefundPrice { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public int WorkflowStatusID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual ClientCompany ClientCompany { get; set; }
        public virtual ClientUser ClientUser { get; set; }
        public virtual Company Company { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductSpecification ProductSpecification { get; set; }
        public virtual WorkflowStatus WorkflowStatus { get; set; }
    }
}
