//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DCFlowDataDetail : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int DCFlowDataID { get; set; }
        public int DBContractID { get; set; }
        public string ContractCode { get; set; }
        public Nullable<bool> IsTempContract { get; set; }
        public int HospitalID { get; set; }
        public string HospitalName { get; set; }
        public int ClientUserID { get; set; }
        public string ClientUserName { get; set; }
        public Nullable<int> InChargeUserID { get; set; }
        public string InChargeUserFullName { get; set; }
        public Nullable<int> UnitOfMeasurementID { get; set; }
        public string UnitName { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int SaleQty { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual DCFlowData DCFlowData { get; set; }
        public virtual DBContract DBContract { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
