//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DepartmentProductSalesPlan : IEntityExtendedProperty
    {
        public DepartmentProductSalesPlan()
        {
            this.DepartmentProductSalesBonus = new HashSet<DepartmentProductSalesBonus>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public int ProductID { get; set; }
        public bool IsFixedOfInside { get; set; }
        public Nullable<double> FixedRatioOfInside { get; set; }
        public bool IsFixedOfOutside { get; set; }
        public Nullable<double> FixedRatioOfOutside { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual Department Department { get; set; }
        public virtual ICollection<DepartmentProductSalesBonus> DepartmentProductSalesBonus { get; set; }
        public virtual Product Product { get; set; }
    }
}
