//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DeptDistrict : IEntityExtendedProperty
    {
        public DeptDistrict()
        {
            this.Department = new HashSet<Department>();
            this.DeptMarket = new HashSet<DeptMarket>();
        }
    
        public int ID { get; set; }
        public int DepartmentTypeID { get; set; }
        public string DistrictName { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return false; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return false; } }
    	public bool HasColumnCreatedBy { get { return false; } }
    	public bool HasColumnLastModifiedOn { get { return false; } }
    	public bool HasColumnLastModifiedBy { get { return false; } }
    
    
        public virtual ICollection<Department> Department { get; set; }
        public virtual ICollection<DeptMarket> DeptMarket { get; set; }
    }
}
