//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Hospital : IEntityExtendedProperty
    {
        public Hospital()
        {
            this.ClientFlowData = new HashSet<ClientFlowData>();
            this.DBClientBonusHospital = new HashSet<DBClientBonusHospital>();
            this.DBContractHospital = new HashSet<DBContractHospital>();
            this.DCFlowData = new HashSet<DCFlowData>();
            this.DCFlowDataDetail = new HashSet<DCFlowDataDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HospitalCodeID { get; set; }
        public string HospitalName { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual ICollection<ClientFlowData> ClientFlowData { get; set; }
        public virtual ICollection<DBClientBonusHospital> DBClientBonusHospital { get; set; }
        public virtual ICollection<DBContractHospital> DBContractHospital { get; set; }
        public virtual ICollection<DCFlowData> DCFlowData { get; set; }
        public virtual ICollection<DCFlowDataDetail> DCFlowDataDetail { get; set; }
        public virtual HospitalCode HospitalCode { get; set; }
    }
}
