//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ProcureOrderApplicationImportData : IEntityExtendedProperty
    {
        public ProcureOrderApplicationImportData()
        {
            this.ProcureOrderAppDetailImportData = new HashSet<ProcureOrderAppDetailImportData>();
        }
    
        public int ID { get; set; }
        public int ProcureOrderApplicationImportFileLogID { get; set; }
        public int ProcureOrderApplicationID { get; set; }
        public string OrderCode { get; set; }
        public string SupplierName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime EstDeliveryDate { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return false; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return false; } }
    	public bool HasColumnLastModifiedBy { get { return false; } }
    
    
        public virtual ICollection<ProcureOrderAppDetailImportData> ProcureOrderAppDetailImportData { get; set; }
        public virtual ProcureOrderApplicationImportFileLog ProcureOrderApplicationImportFileLog { get; set; }
    }
}
