//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SaleOrderType : IEntityExtendedProperty
    {
        public SaleOrderType()
        {
            this.SalesOrderApplication = new HashSet<SalesOrderApplication>();
            this.ClientRefundApplication = new HashSet<ClientRefundApplication>();
            this.ClientInvoice = new HashSet<ClientInvoice>();
            this.DBClientInvoice = new HashSet<DBClientInvoice>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return false; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return false; } }
    	public bool HasColumnCreatedBy { get { return false; } }
    	public bool HasColumnLastModifiedOn { get { return false; } }
    	public bool HasColumnLastModifiedBy { get { return false; } }
    
    
        public virtual ICollection<SalesOrderApplication> SalesOrderApplication { get; set; }
        public virtual ICollection<ClientRefundApplication> ClientRefundApplication { get; set; }
        public virtual ICollection<ClientInvoice> ClientInvoice { get; set; }
        public virtual ICollection<DBClientInvoice> DBClientInvoice { get; set; }
    }
}
