//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SalesOrderApplicationImportData : IEntityExtendedProperty
    {
        public SalesOrderApplicationImportData()
        {
            this.SalesOrderAppDetailImportData = new HashSet<SalesOrderAppDetailImportData>();
            this.ClientSaleApplicationImportData = new HashSet<ClientSaleApplicationImportData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SalesOrderApplicationID { get; set; }
        public string SaleOrderType { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> SaleApplicationImportFileLogID { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return false; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual ICollection<SalesOrderAppDetailImportData> SalesOrderAppDetailImportData { get; set; }
        public virtual ICollection<ClientSaleApplicationImportData> ClientSaleApplicationImportData { get; set; }
    }
}
