//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SupplierInvoiceSettlementDetail : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int SupplierInvoiceSettlementID { get; set; }
        public int SupplierID { get; set; }
        public int SupplierInvoiceID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal InvoiceAmount { get; set; }
        public Nullable<int> AppPaymentID { get; set; }
        public Nullable<int> CanceledAppPaymentID { get; set; }
        public decimal PayAmount { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual Supplier Supplier { get; set; }
        public virtual SupplierInvoice SupplierInvoice { get; set; }
        public virtual SupplierInvoiceSettlement SupplierInvoiceSettlement { get; set; }
        public virtual ApplicationPayment ApplicationPayment { get; set; }
        public virtual ApplicationPayment ApplicationPayment1 { get; set; }
    }
}
