//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class TransportFee : IEntityExtendedProperty
    {
        public int ID { get; set; }
        public int TransportFeeType { get; set; }
        public int TransportCompanyID { get; set; }
        public string TransportCompanyNumber { get; set; }
        public string Driver { get; set; }
        public string DriverTelephone { get; set; }
        public string StartPlace { get; set; }
        public string StartPlaceTelephone { get; set; }
        public string EndPlace { get; set; }
        public string EndPlaceTelephone { get; set; }
        public decimal Fee { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual TransportCompany TransportCompany { get; set; }
    }
}
