//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhongDing.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Warehouse : IEntityExtendedProperty
    {
        public Warehouse()
        {
            this.ProcureOrderAppDetail = new HashSet<ProcureOrderAppDetail>();
            this.StockInDetail = new HashSet<StockInDetail>();
            this.StockOutDetail = new HashSet<StockOutDetail>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string WarehouseCode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
    	// Implements IEntityExtendedProperty
    	public string DefaultOrderColumnName { get { return "id"; } }
    	public bool HasColumnIsDeleted { get { return true; } }
    	public bool HasColumnDeletedOn { get { return false; } }
    	public bool HasColumnCreatedOn { get { return true; } }
    	public bool HasColumnCreatedBy { get { return true; } }
    	public bool HasColumnLastModifiedOn { get { return true; } }
    	public bool HasColumnLastModifiedBy { get { return true; } }
    
    
        public virtual Company Company { get; set; }
        public virtual SaleType SaleType { get; set; }
        public virtual ICollection<ProcureOrderAppDetail> ProcureOrderAppDetail { get; set; }
        public virtual ICollection<StockInDetail> StockInDetail { get; set; }
        public virtual ICollection<StockOutDetail> StockOutDetail { get; set; }
    }
}
