CREATE TABLE [dbo].[CashFlowBaseData] (
    [ID]                         INT      IDENTITY (1, 1) NOT NULL,
    [CashFlowDate]               DATETIME NOT NULL,
    [MoneyBalanceAll]            MONEY    NOT NULL,
    [MoneyBalancePersonal]       MONEY    NOT NULL,
    [MoneyBalanceCompany]        MONEY    NOT NULL,
    [AttachedModeIncome]         MONEY    NOT NULL,
    [SupplierCautionMoneyIncome] MONEY    NOT NULL,
    [ClientCautionMoneyIncome]   MONEY    NOT NULL,
    [BorrowMoneyIncome]          MONEY    NOT NULL,
    [Salary]                     MONEY    NOT NULL,
    [BusinessPercentage]         MONEY    NOT NULL,
    [Reward]                     MONEY    NOT NULL,
    [Reimbursement]              MONEY    NOT NULL,
    [BorrowMoney]                MONEY    NOT NULL,
    [CautionMoneyPayToSupplier]  MONEY    NOT NULL,
    [CautionMoneyReturnToClient] MONEY    NOT NULL,
    [ProductPromotionRebates]    MONEY    NOT NULL,
    [ManagedDistributionFee]     MONEY    NOT NULL,
    [Other]                      MONEY    NOT NULL,
    [FMRefund]                   MONEY    NOT NULL,
    [IsDeleted]                  BIT      CONSTRAINT [DF__CashFlowB__IsDel__707E9C7C] DEFAULT ((0)) NOT NULL,
    [CreatedOn]                  DATETIME CONSTRAINT [DF__CashFlowB__Creat__7172C0B5] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                  INT      NULL,
    [LastModifiedOn]             DATETIME NULL,
    [LastModifiedBy]             INT      NULL,
    [DaBaoRefund]                MONEY    NOT NULL,
    CONSTRAINT [PK__CashFlow__3214EC27813EF5C6] PRIMARY KEY CLUSTERED ([ID] ASC)
);

