CREATE TABLE [dbo].[ClientCautionMoney] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [DepartmentID]           INT            NOT NULL,
    [ClientUserID]           INT            NOT NULL,
    [ProductID]              INT            NOT NULL,
    [ProductSpecificationID] INT            NOT NULL,
    [CautionMoneyTypeID]     INT            NOT NULL,
    [EndDate]                DATETIME       NOT NULL,
    [IsDeleted]              BIT            NOT NULL,
    [CreatedOn]              DATETIME       NOT NULL,
    [CreatedBy]              INT            NULL,
    [LastModifiedOn]         DATETIME       NULL,
    [LastModifiedBy]         INT            NULL,
    [WorkflowStatusID]       INT            NOT NULL,
    [IsStop]                 BIT            NOT NULL,
    [StoppedOn]              DATETIME       NULL,
    [StoppedBy]              INT            NULL,
    [Remark]                 NVARCHAR (256) NULL,
    [CompanyID]              INT            NOT NULL,
    [Payer]                  NVARCHAR (256) NULL,
    CONSTRAINT [PK__ClientCa__3214EC270FE0E596] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ClientCautionMoney_CautionMoneyTypeID] FOREIGN KEY ([CautionMoneyTypeID]) REFERENCES [dbo].[CautionMoneyType] ([ID]),
    CONSTRAINT [FK_ClientCautionMoney_ClientUserID] FOREIGN KEY ([ClientUserID]) REFERENCES [dbo].[ClientUser] ([ID]),
    CONSTRAINT [FK_ClientCautionMoney_CompanyID] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Company] ([ID]),
    CONSTRAINT [FK_ClientCautionMoney_DepartmentID] FOREIGN KEY ([DepartmentID]) REFERENCES [dbo].[Department] ([ID]),
    CONSTRAINT [FK_ClientCautionMoney_ProductID] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ID]),
    CONSTRAINT [FK_ClientCautionMoney_ProductSpecificationID] FOREIGN KEY ([ProductSpecificationID]) REFERENCES [dbo].[ProductSpecification] ([ID])
);

