CREATE TABLE [dbo].[ClientFlowData] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [ImportFileLogID]        INT            NULL,
    [ClientUserID]           INT            NOT NULL,
    [ClientCompanyID]        INT            NOT NULL,
    [SettlementDate]         DATETIME       NOT NULL,
    [ProductID]              INT            NOT NULL,
    [ProductName]            NVARCHAR (255) NULL,
    [ProductCode]            NVARCHAR (50)  NULL,
    [ProductSpecificationID] INT            NOT NULL,
    [ProductSpecification]   NVARCHAR (50)  NULL,
    [SaleDate]               DATETIME       NOT NULL,
    [SaleQty]                INT            NOT NULL,
    [FactoryName]            NVARCHAR (100) NULL,
    [HospitalID]             INT            NULL,
    [FlowTo]                 NVARCHAR (255) NULL,
    [HospitalTypeID]         INT            NULL,
    [DeptMarketID]           INT            NULL,
    [MarketName]             NVARCHAR (50)  NULL,
    [CreatedOn]              DATETIME       CONSTRAINT [DF_ClientFlowData_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              INT            NULL,
    CONSTRAINT [PK_ClientFlowData] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ClientFlowData_ClientCompany] FOREIGN KEY ([ClientCompanyID]) REFERENCES [dbo].[ClientCompany] ([ID]),
    CONSTRAINT [FK_ClientFlowData_ClientUser] FOREIGN KEY ([ClientUserID]) REFERENCES [dbo].[ClientUser] ([ID]),
    CONSTRAINT [FK_ClientFlowData_DeptMarket] FOREIGN KEY ([DeptMarketID]) REFERENCES [dbo].[DeptMarket] ([ID]),
    CONSTRAINT [FK_ClientFlowData_Hospital] FOREIGN KEY ([HospitalID]) REFERENCES [dbo].[Hospital] ([ID]),
    CONSTRAINT [FK_ClientFlowData_HospitalType] FOREIGN KEY ([HospitalTypeID]) REFERENCES [dbo].[HospitalType] ([ID]),
    CONSTRAINT [FK_ClientFlowData_ImportFileLog] FOREIGN KEY ([ImportFileLogID]) REFERENCES [dbo].[ImportFileLog] ([ID]),
    CONSTRAINT [FK_ClientFlowData_Product] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ID]),
    CONSTRAINT [FK_ClientFlowData_ProductSpecification] FOREIGN KEY ([ProductSpecificationID]) REFERENCES [dbo].[ProductSpecification] ([ID])
);

