CREATE TABLE [dbo].[ClientTaskRefundApplication] (
    [ID]                     INT      IDENTITY (1, 1) NOT NULL,
    [CompanyID]              INT      NOT NULL,
    [ClientUserID]           INT      NOT NULL,
    [ClientCompanyID]        INT      NOT NULL,
    [ProductID]              INT      NOT NULL,
    [ProductSpecificationID] INT      NOT NULL,
    [TaskQty]                INT      NOT NULL,
    [StockOutQty]            INT      NOT NULL,
    [UseFlowData]            BIT      NULL,
    [BackQty]                INT      NULL,
    [RefundPrice]            MONEY    NULL,
    [RefundAmount]           MONEY    NULL,
    [RefundDate]             DATETIME NULL,
    [WorkflowStatusID]       INT      NOT NULL,
    [IsDeleted]              BIT      CONSTRAINT [DF_ClientTaskRefundApplication_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedOn]              DATETIME CONSTRAINT [DF_ClientTaskRefundApplication_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              INT      NULL,
    [LastModifiedOn]         DATETIME NULL,
    [LastModifiedBy]         INT      NULL,
    CONSTRAINT [PK_ClientTaskRefundApplication] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ClientTaskRefundApplication_ClientCompany] FOREIGN KEY ([ClientCompanyID]) REFERENCES [dbo].[ClientCompany] ([ID]),
    CONSTRAINT [FK_ClientTaskRefundApplication_ClientUser] FOREIGN KEY ([ClientUserID]) REFERENCES [dbo].[ClientUser] ([ID]),
    CONSTRAINT [FK_ClientTaskRefundApplication_Company] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[Company] ([ID]),
    CONSTRAINT [FK_ClientTaskRefundApplication_Product] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ID]),
    CONSTRAINT [FK_ClientTaskRefundApplication_ProductSpecification] FOREIGN KEY ([ProductSpecificationID]) REFERENCES [dbo].[ProductSpecification] ([ID]),
    CONSTRAINT [FK_ClientTaskRefundApplication_WorkflowStatus] FOREIGN KEY ([WorkflowStatusID]) REFERENCES [dbo].[WorkflowStatus] ([ID])
);

