CREATE TABLE [dbo].[FixedAssets] (
    [ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [Code]                    NVARCHAR (256) NOT NULL,
    [FixedAssetsTypeID]       INT            NOT NULL,
    [Name]                    NVARCHAR (256) NOT NULL,
    [Unit]                    NVARCHAR (256) NULL,
    [Quantity]                INT            NOT NULL,
    [Specification]           NVARCHAR (256) NULL,
    [ProducingArea]           NVARCHAR (256) NULL,
    [Manufacturer]            NVARCHAR (256) NULL,
    [UseStatus]               INT            NOT NULL,
    [DepartmentID]            INT            NOT NULL,
    [UsePeople]               NVARCHAR (256) NULL,
    [StorageLocationID]       INT            NOT NULL,
    [DepreciationType]        INT            NOT NULL,
    [OriginalValue]           MONEY          NOT NULL,
    [StartUsedDate]           DATETIME       NOT NULL,
    [EstimateNetSalvageValue] MONEY          NOT NULL,
    [EstimateUsedYear]        INT            NOT NULL,
    [Comment]                 NVARCHAR (256) NULL,
    [IsDeleted]               BIT            CONSTRAINT [DF__FixedAsse__IsDel__26509D48] DEFAULT ((0)) NOT NULL,
    [CreatedOn]               DATETIME       CONSTRAINT [DF__FixedAsse__Creat__2744C181] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]               INT            NULL,
    [LastModifiedOn]          DATETIME       NULL,
    [LastModifiedBy]          INT            NULL,
    CONSTRAINT [PK__FixedAss__3214EC277F5BA6E0] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FixedAssets_DepartmentID] FOREIGN KEY ([DepartmentID]) REFERENCES [dbo].[Department] ([ID]),
    CONSTRAINT [FK_FixedAssets_FixedAssetsTypeID] FOREIGN KEY ([FixedAssetsTypeID]) REFERENCES [dbo].[FixedAssetsType] ([ID]),
    CONSTRAINT [FK_FixedAssets_StorageLocationID] FOREIGN KEY ([StorageLocationID]) REFERENCES [dbo].[StorageLocation] ([ID])
);

